development:  
  adapter: postgresql
  encoding: unicode
  database: aleksian
  pool: 5
  host: localhost
  port: 5432
  username: user
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: aleksian_test
  pool: 5
  host: localhost
  port: 5432
  username: user
  password: 123